// AUTO-GENERATED by scripts/sync-model-limits.mjs — do not edit by hand.
// Source: https://models.dev/api.json (provider "zai", fallback "zhipuai").
// Verified: 2026-10-05
//
// Z.ai's API returns no context window, so this table is the source of truth for
// context sizing. Regenerate with `pnpm run models:sync`.

export interface ModelCapabilityEntry {
  maxInputTokens: number;
  maxOutputTokens?: number;
}

export const MODEL_TOKEN_LIMITS: Record<string, ModelCapabilityEntry> = {
  'glm-4.5': { maxInputTokens: 131072, maxOutputTokens: 98304 },
    // capabilities: vision=false toolCalling=true
  'glm-4.5-air': { maxInputTokens: 131072, maxOutputTokens: 98304 },
    // capabilities: vision=false toolCalling=true
  'glm-4.5-flash': { maxInputTokens: 131072, maxOutputTokens: 98304 },
    // capabilities: vision=false toolCalling=true
  'glm-4.5v': { maxInputTokens: 64000, maxOutputTokens: 16384 },
    // capabilities: vision=true toolCalling=true
  'glm-4.6': { maxInputTokens: 204800, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-4.6v': { maxInputTokens: 128000, maxOutputTokens: 32768 },
    // capabilities: vision=true toolCalling=true
  'glm-4.6v-flash': { maxInputTokens: 128000, maxOutputTokens: 32768 },
    // capabilities: vision=true toolCalling=true
  'glm-4.7': { maxInputTokens: 204800, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-4.7-flash': { maxInputTokens: 200000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-4.7-flashx': { maxInputTokens: 200000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5': { maxInputTokens: 204800, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5-turbo': { maxInputTokens: 200000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5.1': { maxInputTokens: 200000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5.2': { maxInputTokens: 1000000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5.3': { maxInputTokens: 1000000, maxOutputTokens: 131072 },
    // capabilities: vision=false toolCalling=true
  'glm-5.3-flash': { maxInputTokens: 1000000, maxOutputTokens: 131072 },
    // capabilities: vision=true toolCalling=true
  'glm-5.3-flashx': { maxInputTokens: 1000000, maxOutputTokens: 131072 },
    // capabilities: vision=true toolCalling=true
  'glm-5v-turbo': { maxInputTokens: 200000, maxOutputTokens: 131072 },
    // capabilities: vision=true toolCalling=true
};

/** Models that accept image input, per models.dev modalities.input. */
export const VISION_MODEL_IDS: ReadonlySet<string> = new Set([
  'glm-4.5v',
  'glm-4.6v',
  'glm-4.6v-flash',
  'glm-5.3-flash',
  'glm-5.3-flashx',
  'glm-5v-turbo',
]);
